### ISSUE TITLE
Ошибка 404

### ISSUE THREAD

**Issue by mediafoks** [WebTolk/WT-Contact-with-fields-Joomla-5-package#1]
Добрый день!
Очередной прекрасный плагин. НО
Если контакт существует, но не опубликован, то его вывод выдает 404 ошибку. Нужна проверка перед выводом на опубликован контакт или нет.

**Comment by sergeytolkachyov** [comment]
Здравствуйте.  Вы шорткодом вставляете? Или блок автора?

**Comment by mediafoks** [comment]
> Здравствуйте. Вы шорткодом вставляете? Или блок автора?

Вот так
```{wt_contact_wf contact_id=5 tmpl=default}```

**Comment by sergeytolkachyov** [comment]
Тогда эту ошибку выдаёт модель com_contact Joomla, а не плагин. При работе с шорткодом я использую модель компонента. Так, а шорткод руками пишете или с помощью плагина кнопки редактора?

**Comment by mediafoks** [comment]
> Тогда эту ошибку выдаёт модель com_contact Joomla, а не плагин. При работе с шорткодом я использую модель компонента. Так, а шорткод руками пишете или с помощью плагина кнопки редактора?

Я и вставляю с помощью кнопки редактора "WT Контакт". Нажимаю кнопку, открывается модалка. Я выбираю какой-нибудь контакт. Вот и всё. Но если этот контакт не опубликован, то 404 ошибка.

**Comment by sergeytolkachyov** [comment]
Тогда добавлю, что неопубликованные скрывал в модалке.

**Comment by mediafoks** [comment]
> Тогда добавлю, что неопубликованные скрывал в модалке.

Этого тоже недостаточно.
Вот представьте, например сейчас контакт опубликован, т.е. он актуален, я его вывел шорткодом в какие-то кучу материалов. В один момент этот контакт перестал быть актуальным и я его просто снял с публикации или вообще удалил. Но при этом шорткоды в материалах останутся. В итоге получим 404 экран.

**Comment by sergeytolkachyov** [comment]
Я хотел избежать полного копирования кода модели в плагин, видимо, не получится )) Принято.

**Comment by sergeytolkachyov** [comment]
Fixed in v.1.0.1
