### ISSUE TITLE
target _blank ? Просьба добавить функционал

### ISSUE THREAD

**Issue by mediafoks** [WebTolk/WT-Contact-with-fields-Joomla-5-package#3]
День добрый!
По умолчанию Контакт открывается в новом окне, в шаблоне жестко зашито. 
``<a href="<?php echo $contact_sef_link; ?>" target="_blank" ...``

Хорошо бы в настройках плагина добавить чекбокс, открывать в новом окне или нет. Неохота из-за такой мелочи еще один шаблон заводить.

**Comment by sergeytolkachyov** [comment]
Добрый день. Можно убрать target _blank. Сделайте PR. Я приму.

**Comment by sergeytolkachyov** [comment]
Закрыто в версии 1.0.2
